---

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: true

- name: install nginx and basic packages 
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - nginx
    - apache2-utils
    - python3-passlib
  become: true

- name: copy openhab config to site-enabled
  copy:
    src: openhab
    dest: /etc/nginx/sites-enabled/openhab
  become: true

- name: remove default site file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: set htpasswd user/password
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: krzysztof
    password: "{{ nginx_passwd }}"
    owner: www-data
    group: root
    mode: 0640
  become: true

- name: copy ssl certificates
  copy:
    src: "{{ item }}"
    dest: /etc/ssl/certs
    owner: root
    group: root
  with_fileglob:
    - "{{ secrets_directory }}/nginx/openhab*"
  become: true

- name: start nginx service
  service:
    name: nginx
    state: started
    enabled: yes
  become: true


