---
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  become: true

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} edge
  become: true

- name: Install list of packages
  apt:
    name: "{{ pkgs }}"
    state: present
    update_cache: yes
  vars:
    pkgs:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - docker-ce
  become: true
