---
- hosts: all
  roles:
    - basic
    - docker-install
    - nameserver
- hosts: asrock
  vars_files:
    - ~/openhab-smarthome-server/oh-data/secrets/secrets.yml
  connection: local
  roles:
    - molecule
    - vagrant
    - routes
    - partition
    - xeoma
    - mosquitto-mqtt
    - broadlink
    - nut