---
- name: add APT key for openhab
  apt_key:
    url: https://openhab.jfrog.io/artifactory/api/gpg/key/public
    state: present
  become: true

- name: add openhab2 stable repository
  apt_repository:
    repo: deb https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable main
    state: present
    mode: 0666
  become: true

- name: add openhab2 testing repository
  apt_repository:
    repo: deb https://openhab.jfrog.io/openhab/openhab-linuxpkg testing main
    state: present
    mode: 0666    
  become: true

- name: install openhab2.5 release
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - openhab2=2.5.3-1
    - openhab2-addons=2.5.3-1
    update_cache: yes
    state: present
  become: true

- name: add java8 repository
  apt_repository:
    repo: ppa:openjdk-r/ppa
    mode: 0666
  become: true
  notify: install java8

