---
- name: add APT key for openhab
  apt_key:
    url: https://bintray.com/user/downloadSubjectPublicKey?username=openhab
    state: present
  become: true

- name: add openhab2 stable repository
  apt_repository:
    repo: deb https://dl.bintray.com/openhab/apt-repo2 stable main
    state: present
    mode: 0666
  become: true

- name: add openhab2 testing repository
  apt_repository:
    repo: deb https://openhab.jfrog.io/openhab/openhab-linuxpkg testing main
    state: present
    mode: 0666    
  become: true

- name: install openhab2.4 release
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - openhab2=2.4.0-1
    - openhab2-addons=2.4.0-1
    update_cache: yes
    state: present
  become: true

- name: add java8 repository
  apt_repository:
    repo: ppa:openjdk-r/ppa
    mode: 0666
  become: true
  notify: install java8

