---
- name: Copy in the openhab backup file
  copy:
    src: "{{ item }}"
    dest: "/tmp/openhab2-backup.zip"
    owner: openhab
    group: openhab
    mode: 0644
  with_fileglob:
    - openhab2-backup*.zip
  become: true

- name: install pexpect package
  pip:
    name: pexpect
    state: present
  become: true

- name: check if restore of openhab was done
  command: ls -1 /etc/openhab2/items
  register: items
  changed_when: "'Konstancin.items' not in items.stdout"
  notify: restore openhab2 from backup
  become: true

- name: Force notified handlers to run now before restoring files against running openhab2 instance
  meta: flush_handlers

- name: gather service statuses
  service_facts:

- name: update influxdb.cfg in openhab2
  template:
    src: influxdb.cfg.j2
    dest: /etc/openhab2/services/influxdb.cfg
  become: true
  notify: restart service openhab2
