---
- name: set nameserver
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
  become: true

- name: set nameserver for ubuntu16.04
  copy:
    src: tail
    dest: /etc/resolvconf/resolv.conf.d/tail
    mode: 0666
  when: ansible_distribution_release is match ("xenial")
  become: true
  notify: update resolvconf

