---
- name: Install python for Ansible
  raw: test -e /usr/bin/python || \
       (apt -y update && apt install -y python-minimal)
  become: true
  changed_when: false

- name: install packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - unzip
    - htop
    - nmap
    - hping3
    state: present
  become: true

- name: update /etc/hosts file
  blockinfile:
    block: "{{ lookup('file', backup_directory+'/basic/hosts') }}"
    dest: "/etc/hosts"
    marker: "# {mark} ANSIBLE MANAGED BLOCK hosts add"
  become: true

- name: add openhab ip address to /etc/hosts file
  blockinfile:
    block: "{{ openhab_ip_addr }}    openhab"
    dest: "/etc/hosts"
    marker: "# {mark} ANSIBLE MANAGED BLOCK openhab add"
  become: true

- name: set timezone to Europe/Warsaw
  timezone:
    name: Europe/Warsaw
  become: true


# required for influx client installation
- name: Install python PIP
  apt:
    name: python3-pip
    state: present
  become: true

