
- name: grant permissions to openhab user
  command: "influx -username {{ influxdb_admin_user }} -password {{ influxdb_admin_password }} -execute 'GRANT ALL ON openhab_db TO openhab'"

- name: grant permissions to grafana user
  command: "influx -username {{ influxdb_admin_user }} -password {{ influxdb_admin_password }} -execute 'GRANT READ ON openhab_db TO grafana'"

- name: restart influxDB service
  service: 
    name: influxdb
    state: restarted
  become: true

- name: start influxDB service
  service: 
    name: influxdb
    state: started
    enabled: yes
  become: true
