---
- name: configure static route for myopenhab.org
  command: bash -c "ip route add 139.162.171.235 via 192.168.1.2"
  become: true

- name: copy interfaces file
  copy:
    src: interfaces
    dest: /etc/network/interfaces
  become: true
