---
- name: Run jupyter docker
  docker_container:
    name: jupyter
    image: jupyter/minimal-notebook:latest
    privileged: yes
    restart_policy: on-failure
    state: started
    ports:
    - "9988:8888"
    volumes:
    - "/home/krzysztof/projects/jupyter_nooteboks:/home/jovyan/work"
  become: true
