---
# vagrant hostname
vmhostname: openhab-prod

# Grafana Variables
grafana_storage: /var/lib/grafana
grafana_provisioning: "{{ grafana_storage }}/provisioning"
grafana_docker_provisioning: /etc/grafana/provisioning
grafana_provisioning_datasources: "{{ grafana_provisioning }}/datasources"
grafana_provisioning_dashboards: "{{ grafana_provisioning }}/dashboards"
grafana_docker_exposed_ports: "3000:3000"

# Provisioning datasourcs.yml
grafana_provisioning_influxdb_datasource_template: influxdb.yaml.j2
grafana_provisioning_influxdb_datasource: "{{ grafana_provisioning_datasources }}/influxdb.yaml"

# Grafana InfluxDB datasource
grafana_datasource_name: openhab_dom
grafana_url: http://localhost:3000 # Technically deprecated. But would be updated in ./roles/install-grafana/tasks/main.yml
grafana_org_id: 1
grafana_ds_type: influxdb
influxdb_url: https://localhost:8086
data_dir: /vagrant_data

# vcontrold
openhab_ip_addr: 192.168.1.25


# credential variables from below are stored in secrets.yml
# influxdb_admin_user: 
# influxdb_admin_password:
# influxdb_database_name:
# influxdb_openhab_user:
# influxdb_openhab_password:
# influxdb_grafana_user:
# influxdb_grafana_password:
# influxdb_username:
# influxdb_password:
# grafana_user:
# grafana_password:

